version: '3.8'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      - ./.wwebjs_auth:/app/.wwebjs_auth
    restart: unless-stopped
    # Add security options for Chromium
    security_opt:
      - seccomp:unconfined
    # Increase shared memory size for Chromium
    shm_size: '2gb'
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {let d='';r.on('data',(c)=>d+=c);r.on('end',()=>process.exit(JSON.parse(d).status==='running'?0:1))}).on('error',()=>process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s