version: "3.8"

services:
  server:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./.wwebjs_auth:/app/.wwebjs_auth
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    shm_size: "2gb"
