services:
  - type: web
    name: whatsapp-bot
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y chromium
      npm install
    startCommand: node main.js
    envVars:
      - key: RENDER
        value: "true"
    autoDeploy: true
